In [2]:
import numpy as np 
import torch

In [19]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[1, 0, 1],
              [1, 1, 1],
              [0, 1, 0]])
print(A)
print()
print(B)

[[1 2 3]
 [4 5 6]]

[[1 0 1]
 [1 1 1]
 [0 1 0]]


In [20]:
C = np.matmul(A, B)
print(C)

[[ 3  5  3]
 [ 9 11  9]]


In [29]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 1])
np.einsum('i,j->ij', a, b)

array([[ 1,  2,  1],
       [ 2,  4,  2],
       [ 3,  6,  3],
       [ 4,  8,  4],
       [ 5, 10,  5]])

In [22]:
np.einsum('ij,jk->ij', A, B)

array([[ 2,  6,  3],
       [ 8, 15,  6]])