In [2]:
import torch
import math
print(torch.__config__.show())

PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBG

### Constructors

#### Basic Tensors

In [31]:
shape = (2, 3)

print("Uninitialized Tensor")
print(torch.empty(shape))
print()

print("Zeros Tensor")
print(torch.zeros(shape))
print()

print("Ones Tensor")
print(torch.ones(shape))
print()

print("Identity Matrix")
print(torch.eye(shape[1]))
print()

print("Filled Tensor")
print(torch.full(shape, math.pi))
print()

Uninitialized Tensor
tensor([[7.3394e-35, 0.0000e+00, 2.7544e-35],
        [0.0000e+00, 3.1416e+00, 3.1416e+00]])

Zeros Tensor
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones Tensor
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Identity Matrix
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Filled Tensor
tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])



#### 1D Range Based Tensors

In [51]:
print("Range Based")
#[Start, End), Step
print(torch.arange(5, 26, 5))
print(torch.arange(0, 11, 2.5))
print()

print("n-Values in Interval")
#Creates a one-dimensional tensor of size Steps whose values are evenly spaced from [Start, End]
print(torch.linspace(0, 25, 5))
print(torch.linspace(start = -10, end = 10, steps = 10))




Range Based
tensor([ 5, 10, 15, 20, 25])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

n-Values in Interval
tensor([ 0.0000,  6.2500, 12.5000, 18.7500, 25.0000])
tensor([-10.0000,  -7.7778,  -5.5556,  -3.3333,  -1.1111,   1.1111,   3.3333,
          5.5556,   7.7778,  10.0000])


#### Dealing with Random Generators

In [17]:
#Random Tensor 
SEED = 68 
torch.manual_seed(SEED)
torch.rand(3, 4)

tensor([[0.3991, 0.5521, 0.1004, 0.2844],
        [0.9998, 0.7077, 0.8031, 0.2066],
        [0.3589, 0.8509, 0.8753, 0.4669]])

#### Interoperability with Numpy

#### Interoperability with Python Objects

In [27]:
print("Tensor from a python sequence")
print(torch.tensor([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]]))

Tensor from a python sequence
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
