In [1]:
import torch
import math
print(torch.__config__.show())

PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -ope

In [2]:
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

### Constructors

#### Basic Tensors

In [3]:
shape = (2, 3)

print("Uninitialized Tensor")
print(torch.empty(shape))
print()

print("Zeros Tensor")
print(torch.zeros(shape))
print()

print("Ones Tensor")
print(torch.ones(shape))
print()

print("Identity Matrix")
print(torch.eye(shape[1]))
print()

print("Filled Tensor")
print(torch.full(shape, math.pi))
print()

Uninitialized Tensor
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Zeros Tensor
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Ones Tensor
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Identity Matrix
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Filled Tensor
tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])



#### 1D Range Based Tensors

In [4]:
print("Range Based")
#[Start, End), Step
print(torch.arange(5, 26, 5))
print(torch.arange(0, 11, 2.5))
print()

print("n-Values in Interval")

#Creates a one-dimensional tensor of size Steps whose values are evenly spaced from [Start, End]
print(torch.linspace(0, 25, 5))
print(torch.linspace(start = -10, end = 10, steps = 10))

Range Based
tensor([ 5, 10, 15, 20, 25])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

n-Values in Interval
tensor([ 0.0000,  6.2500, 12.5000, 18.7500, 25.0000])
tensor([-10.0000,  -7.7778,  -5.5556,  -3.3333,  -1.1111,   1.1111,   3.3333,
          5.5556,   7.7778,  10.0000])


#### Dealing with Random Generators

In [13]:
#Create a custom Random Number Generator
rng = torch.Generator(device = DEVICE)
#Manually Seed the Generator
rng.manual_seed(271828)


print(torch.rand(1, generator = rng, device = DEVICE))
print(torch.rand(1, generator = rng, device = DEVICE))

#Create a new generator with the same state as the previous RNG 
new_rng = torch.Generator(device = DEVICE)
new_rng.set_state(rng.get_state())

#Both will have the same result
print(torch.rand(1, generator = new_rng, device = DEVICE))
print(torch.rand(1, generator = rng, device = DEVICE))

tensor([0.4649], device='cuda:0')
tensor([0.6382], device='cuda:0')
tensor([0.5321], device='cuda:0')
tensor([0.5321], device='cuda:0')


In [ ]:
#Seed the Global Random Number Generator

#print(torch.defualt_generator.manual_seed(271828))
print(torch.manual_seed(271828))
print(torch.rand(shape))

tensor([[0.3478, 0.7848, 0.6988],
        [0.4897, 0.7965, 0.9054]])


#### Random Sampling

In [ ]:
#From Uniform Distribution on [0, 1)
print(torch.rand(shape))

# From Standard Normal Distribution
print(torch.randn(shape))

tensor([[0.5621, 0.0730, 0.6361],
        [0.6597, 0.8087, 0.4713]])
tensor([[ 0.4476,  2.4351, -1.0493],
        [ 1.6843, -1.2536, -0.4992]])


#### Interoperability with Numpy

The contents for the new object uses the same underlying memory as the source object, thus changes to the source data are reflected in the converted object as well.

In [ ]:
import numpy as np
ndarray = np.arange(2, 11, 2)

#Create a tensor, with the same data as a numpy ndarray
tensor = torch.from_numpy(ndarray)
print(tensor)
ndarray[0] = 13
print(tensor)

#Vice-Versa
tensor = torch.arange(2, 11, 2)
ndarray = tensor.numpy()
print(f"ndarray({ndarray})")
tensor[0] = 13
print(f"ndarray({ndarray})")

tensor([ 2,  4,  6,  8, 10], dtype=torch.int32)
tensor([13,  4,  6,  8, 10], dtype=torch.int32)
ndarray([ 2  4  6  8 10])
ndarray([13  4  6  8 10])


#### Interoperability with Python Objects

In [ ]:
print("Tensor from a python sequence")
print(torch.tensor([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]]))

Tensor from a python sequence
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


### Attributes

### Operations

### Views

### Arithmetic