In [1]:
import torch

In [2]:
print(torch.__version__)
print(torch.__config__)


1.13.1+cu117
<module 'torch.__config__' from '/home/sambhav/bin/anaconda3/envs/ml/lib/python3.9/site-packages/torch/__config__.py'>


In [3]:
# Null Vector is a vector of zeros
print(torch.zeros(10))

# Vector of nan values
print(torch.full((10,), torch.nan))

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])


In [4]:
a = torch.zeros(10)
print(f"Tensor Size in Memory: {a.element_size() * a.nelement()}")

Tensor Size in Memory: 40


In [5]:
# How to get documentation in command line

In [6]:
a = torch.zeros(10)
a[4] = 1
a

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [7]:
torch.hstack([torch.zeros(4), torch.tensor(1), torch.zeros(5)])

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [8]:
torch.arange(10,50)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49])

In [9]:
reversed(torch.arange(10, 15))

tensor([14, 13, 12, 11, 10])

In [10]:
torch.arange(0, 9).reshape((3,3))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [11]:
torch.tensor([1,2,0,0,4,0]).nonzero()

tensor([[0],
        [1],
        [4]])

In [12]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [13]:
torch.rand(3,3,3)

tensor([[[0.4985, 0.8381, 0.1206],
         [0.3779, 0.2118, 0.7416],
         [0.7526, 0.2313, 0.5129]],

        [[0.1444, 0.6800, 0.9803],
         [0.2456, 0.8830, 0.4456],
         [0.4765, 0.2562, 0.7741]],

        [[0.5425, 0.9578, 0.8159],
         [0.1118, 0.0984, 0.4924],
         [0.9178, 0.7354, 0.7846]]])

In [14]:
r = torch.rand(10,10)
print(r.min())
print(r.max())

tensor(0.0085)
tensor(0.9995)


In [15]:
torch.rand(30).mean()

tensor(0.5867)

In [16]:
a = torch.ones(3)
torch.vstack([a for _ in range(3)])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [17]:
torch.hstack([torch.ones(1), torch.ones(1)])

tensor([1., 1.])

In [18]:
def bordered2dArray(n_rows:int, n_cols:int):
    if n_cols <= 2 or n_rows <= 2:
        return torch.ones(n_rows, n_cols) 
    else:
        top_and_bottom = torch.ones(n_cols)
        rows = torch.vstack([torch.hstack([torch.ones(1), torch.zeros(n_cols-2), torch.ones(1)]) for _ in range(n_rows-2)])
        return torch.vstack([top_and_bottom, rows, top_and_bottom])
bordered2dArray(5, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1.]])

In [19]:
torch.nn.functional.pad(torch.tensor([[4, 5, 6]]), (1, 1, 1, 1), "constant", 0)

tensor([[0, 0, 0, 0, 0],
        [0, 4, 5, 6, 0],
        [0, 0, 0, 0, 0]])

In [20]:
print(0*torch.nan)
print(torch.nan == torch.nan)
print(torch.inf > torch.nan)
print(torch.nan - torch.nan)
print(torch.nan in set([torch.nan]))
print(.3 == 3*0.1)

nan
False
False
nan
True
False


In [21]:
torch.diag(torch.arange(1, 5), diagonal=-1)

tensor([[0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0]])

In [22]:
c = torch.ones(8, 8)
c[::2, 1::2] = 0
c[1::2, ::2] = 0
c

tensor([[1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.]])